Acceptance tests
MaterializeInc/terraform-provider-materialize pull request #200
Opened 2023-06-13 15:18 UTC by bobbyiliev

Adding more acceptance tests for the following resources:

- [x] Views
- [x] Tables
- [x] Types
- [x] Schemas
- [x] Load generator source

2023-06-13 15:50 UTC, dehume requested changes
Overall looks good. Only thing is some of these resources have additional attributes we can check in state after the apply.

2023-06-13 15:50 UTC, dehume commented on pkg/provider/acceptance_schema_test.go
> +					resource.TestCheckResourceAttr("materialize_schema.test", "name", schemaName),
A couple more attributes to include `database_name` and `qualified_sql_name`

2023-06-13 15:50 UTC, dehume commented on pkg/provider/acceptance_table_test.go
> +					resource.TestCheckResourceAttr("materialize_table.test", "name", tableName),
There are a few other attributes we should track like the `schema_name`, `database_name`, `qualified_sql_name`, `column`

2023-06-13 15:50 UTC, dehume commented on pkg/provider/acceptance_type_test.go
> +					resource.TestCheckResourceAttr("materialize_type.test", "name", typeName),
There are a few other attributes we should track like the `schema_name`, `database_name`, `qualified_sql_name`, `list_properties`, `map_properties`, `category`

2023-06-13 15:50 UTC, dehume commented on pkg/provider/acceptance_view_test.go
> +					resource.TestCheckResourceAttr("materialize_view.test", "name", viewName),
There are a few other attributes we should track like the `schema_name`, `database_name`, `qualified_sql_name`, `statement`

2023-06-14 14:55 UTC, bobbyiliev commented on pkg/provider/acceptance_source_load_generator_test.go
> +					resource.TestCheckResourceAttr("materialize_source_load_generator.test", "name", sourceLoadGeneratorName),
Goot catch! Just added the missing attributes for all of those resources! Let me know if you notice any other issues!

2023-06-14 19:35 UTC, dehume approved these changes

2023-06-14 19:36 UTC, merged